Initial commit of bakery module
Checkmk/ansible-collection-tribe29.checkmk pull request #308
Opened 2023-04-12 14:29 UTC by Max-checkmk

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
There is no bakery module at the moment

## What is the new behavior?

- Bakery module added (options "bake", "sign" and "bake and sign")

## Other information

2023-04-13 14:24 UTC, robin-tribe29 requested changes
I have some remarks about the formatting and documentation.
Nothing terrible, just improvements.
Review of the code will be done separately.

2023-04-13 14:24 UTC, robin-tribe29 commented on plugins/modules/bakery.py
> +- Using the Bakery.
See above.

2023-04-13 14:24 UTC, robin-tribe29 commented on plugins/modules/bakery.py
> +        default: "baked"
Is this the best default? I am genuinely asking.
I always tell users to only use "bake and sign", so they do not end up with unsigned agents.
However, if a user is not signing their agents, that default could cause trouble.

2023-04-13 14:24 UTC, robin-tribe29 commented on plugins/modules/bakery.py
> +    automation_secret: "$SECRET"
I think it is worthwhile to provide examples for all three use cases.
Also, per Ansible philosophy, you should "always mention the state". :)

2023-04-13 14:47 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +short_description: Using the Bakery.
accepted and changed

2023-04-13 14:47 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +version_added: "0.17.1"
changed

2023-04-13 14:47 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +- Using the Bakery.
accepted and changed

2023-04-13 14:50 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +    sign_key_id:
It's shorter this way. In the API it's even shorter (just key_id and passphrase). But i wouldn't mind if we take the longer one

2023-04-13 14:50 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +    automation_secret: "$SECRET"
Added an example for each use case.

2023-04-13 14:53 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +        default: "baked"
I use bake only because in a fresh installation there is no signature key and at the moment there is no way with the RESTAPI to configure one.
If someone has a already configured site (s)he has to change the task anyway (adding key_id and passphrase).

2023-04-17 14:37 UTC, robin-checkmk requested changes

2023-04-17 14:37 UTC, robin-checkmk commented on plugins/modules/bakery.py
> +        default: "baked"
Hm, fair. Without preparation, this module would fail. Okay, I am fine with the default for now.
We can revisit this at a later time, depending on feedback.

2023-05-03 10:21 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +- name: "Sign and Bake all agents."
Changed ;)

2023-05-04 06:27 UTC, lgetwan requested changes
Good job, Max! 
I added one change request regarding the HTTP 204 return code.
There's one general downside of the module: It always bakes and/or signs, no matter if it's needed or not (idempotency), but I also have no idea how to find out if baking is needed using the API. Probably, you should mention that in the docs.

2023-05-04 08:11 UTC, Max-checkmk commented on plugins/modules/bakery.py
> +        200: (True, False, "The operation was done successfully."),
Added 204

2023-05-04 08:14 UTC, lgetwan approved these changes

2023-05-04 08:16 UTC, lgetwan approved these changes
Perfect!

2023-05-04 08:20 UTC, robin-checkmk approved these changes

2023-05-04 08:20 UTC, robin-checkmk commented
This will be merged in preparation for `0.21.0`. :+1:

2023-05-08 07:42 UTC, merged